projects:
  app:
    schemaPath: src/schemas/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:${env:APP_PORT}
  prisma:
    schemaPath: src/database/prisma.generated.graphql
    extensions:
      prisma: src/database/prisma.yml
