projects:
  app:
    schemaPath: "src/api/schema.graphql"
    extensions:
      endpoints:
        default: "http://localhost:${env:APP_PORT}"
  database:
    schemaPath: "src/generated/prisma.graphql"
    extensions:
      prisma: .prisma.yml
