# the name for the service (will be part of the service's HTTP endpoint)
service: prueba

# the cluster and stage the service is deployed to
stage: dev

# to disable authentication:
# disableAuth: true
secret: mysecret123

# the file path pointing to your data model
datamodel: src/api/datamodel.graphql

cluster: local
